name: Gerar APK do Pet
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Compilar APK
        run: chmod +x gradlew && ./gradlew assembleDebug
      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-pet-apk
          path: app/build/outputs/apk/debug/app-debug.apk
